/**
 *   Copyright 2013 Nekorp
 *
 *Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License
 */
package org.nekorp.workflow.desktop.view;

import org.nekorp.workflow.desktop.view.resource.DialogFactory;
import org.nekorp.workflow.desktop.view.resource.ShapeView;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

/**
 *
 */
@Component
public class AutoDamageView extends ApplicationView {

    @Autowired
    @Qualifier("captureDetailDialogFactory")
    private DialogFactory dialogFactory;
    @Autowired
    javax.swing.JFrame mainFrame;
    private ShapeView currentView;
    private int boundsX;
    private int boundsY;
    /**
     * Creates new form AutoDamageView
     */
    public AutoDamageView() {
        super();
    }
    
    @Override
    public void iniciaVista() {
        initComponents();
    }

    @Override
    public void setEditableStatus(boolean value) {
        //no hacer nada aun.
    }

    @Override
    public ViewValidIndicator getValidInidicator() {
        return null;
    }
    
    public void changeView(ShapeView view) {
        if (currentView != null) {
            content.remove(currentView);
        }
        currentView = view;
        resizeCurrentView();
        content.add(currentView, -1);
        content.repaint();
    }
    
    private void resizeCurrentView() {
        boundsX = (content.getWidth() - currentView.getShapeWidth()) / 2;
        //boundsX = 60;
        boundsY = (content.getHeight() - currentView.getShapeHeight()) / 2;
        //boundsY = 50;
        currentView.setBounds(boundsX, boundsY, currentView.getShapeWidth(), currentView.getShapeHeight());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JLayeredPane();

        content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentMouseClicked(evt);
            }
        });
        content.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                contentComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMouseClicked
        if (currentView.shapeContains(evt.getX() - boundsX, evt.getY() - boundsY)) {
            dialogFactory.createDialog(mainFrame, true).setVisible(true);
        }
    }//GEN-LAST:event_contentMouseClicked

    private void contentComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_contentComponentResized
        if (currentView != null) {
            resizeCurrentView();
        }
    }//GEN-LAST:event_contentComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane content;
    // End of variables declaration//GEN-END:variables

}
