/**
 *   Copyright 2013 Nekorp
 *
 *Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License
 */
package org.nekorp.workflow.desktop.view;

import org.nekorp.workflow.desktop.view.resource.ShapeView;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

/**
 *
 */
@Component("inventarioDamage")
public class InventarioDamage extends ApplicationView {

    @Autowired
    @Qualifier("autoRightView")
    private ShapeView autoRightView;
    @Autowired
    @Qualifier("autoLeftView")
    private ShapeView autoLeftView;
    @Autowired
    @Qualifier("autoFrontView")
    private ShapeView autoFrontView;
    @Autowired
    @Qualifier("autoRearView")
    private ShapeView autoRearView;
    @Autowired
    private AutoDamageView damageView;
    /**
     * Creates new form InventarioDamage
     */
    public InventarioDamage() {
    }
    
    @Override
    public void iniciaVista() {
        initComponents();
        damageView.iniciaVista();
        this.content.add(damageView);
        damageView.changeView(autoRightView);
    }

    @Override
    public void setEditableStatus(boolean value) {
        //aun nada
    }

    @Override
    public ViewValidIndicator getValidInidicator() {
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        derecha = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        frontal = new javax.swing.JButton();
        trasera = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        derecha.setText("Derecha");
        derecha.setFocusable(false);
        derecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        derecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });
        jToolBar1.add(derecha);

        izquierda.setText("Izquierda");
        izquierda.setFocusable(false);
        izquierda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        izquierda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });
        jToolBar1.add(izquierda);

        frontal.setText("Frontal");
        frontal.setFocusable(false);
        frontal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        frontal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        frontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontalActionPerformed(evt);
            }
        });
        jToolBar1.add(frontal);

        trasera.setText("Trasera");
        trasera.setFocusable(false);
        trasera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trasera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        trasera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traseraActionPerformed(evt);
            }
        });
        jToolBar1.add(trasera);

        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed
        damageView.changeView(autoRightView);
    }//GEN-LAST:event_derechaActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        damageView.changeView(autoLeftView);
    }//GEN-LAST:event_izquierdaActionPerformed

    private void frontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontalActionPerformed
        damageView.changeView(autoFrontView);
    }//GEN-LAST:event_frontalActionPerformed

    private void traseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traseraActionPerformed
        damageView.changeView(autoRearView);
    }//GEN-LAST:event_traseraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton derecha;
    private javax.swing.JButton frontal;
    private javax.swing.JButton izquierda;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton trasera;
    // End of variables declaration//GEN-END:variables

}
