/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo.view;

import java.util.LinkedList;
import java.util.List;
import prototipo.modelo.bitacora.Bitacora;
import prototipo.modelo.bitacora.Evento;
import prototipo.modelo.bitacora.EventoEntrega;
import prototipo.modelo.bitacora.EventoGeneral;

/**
 *
 * @author Marisa
 */
public class BitacoraView extends javax.swing.JPanel {

    /**
     * Creates new form Bitacora
     */
    public BitacoraView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        agregarBitacora = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradas = new javax.swing.JPanel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        agregarBitacora.setText("Nueva Entrada");
        agregarBitacora.setFocusable(false);
        agregarBitacora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarBitacora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBitacoraActionPerformed(evt);
            }
        });
        jToolBar1.add(agregarBitacora);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        entradas.setLayout(new javax.swing.BoxLayout(entradas, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(entradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBitacoraActionPerformed
        Object[] possibilities = {"Entrada de Auto", "Salida de Auto", "Otro"};
        String s = (String)javax.swing.JOptionPane.showInputDialog(
                            this,
                            "Eliga el evento",
                            "Seleccion evento",
                            javax.swing.JOptionPane.PLAIN_MESSAGE,
                            null,
                            possibilities,
                            "Entrega Auto");
        if (s == null) {
            return;
        }
        if (s.compareTo("Otro") == 0) {
            EventoGeneralView entrada = new EventoGeneralView();
            entrada.setBitacora(this);
            this.entradas.add(entrada);
        } else {
            EventoEntregaView entrada = new EventoEntregaView();
            entrada.setBitacora(this);
            entrada.setNombreEvento(s);
            this.entradas.add(entrada);
        }
        //javax.swing.Box.createRigidArea(new java.awt.Dimension(5,0));
        this.updateUI();
    }//GEN-LAST:event_agregarBitacoraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBitacora;
    private javax.swing.JPanel entradas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    //mis variables
    private ServicioView parent;
    //mis metodos
    public void notificaBorrado(javax.swing.JPanel entrada) {
        this.entradas.remove(entrada);
        this.updateUI();
    }
    
    public Bitacora getData(){
        prototipo.modelo.bitacora.Bitacora r = new Bitacora();
        List<Evento> eventos = new LinkedList<>();
        for(java.awt.Component c:this.entradas.getComponents()){
            if (c instanceof EventoView) {
                EventoView obj = (EventoView) c;
                eventos.add(obj.getData());
            }
        }
        r.setEventos(eventos);
        return r;
    }

    public void loadData(Bitacora bitacora) {
        for (Evento obj : bitacora.getEventos()) {
            if (obj instanceof EventoGeneral) {
                EventoGeneral ev = (EventoGeneral) obj;
                EventoGeneralView entrada = new EventoGeneralView();
                entrada.setBitacora(this);
                entrada.loadData(ev);
                this.entradas.add(entrada);
            }
            if (obj instanceof EventoEntrega) {
                EventoEntrega ev = (EventoEntrega) obj;
                EventoEntregaView entrada = new EventoEntregaView();
                entrada.setBitacora(this);
                entrada.loadData(ev);
                this.entradas.add(entrada);
            }
        }
        this.updateUI();
    }

    public void setParent(ServicioView parent) {
        this.parent = parent;
    }
    
}
