/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import prototipo.modelo.bitacora.Evento;
import prototipo.modelo.bitacora.EventoGeneral;

/**
 *
 * @author Marisa
 */
public class EventoGeneralView extends javax.swing.JPanel implements EventoView {

    /**
     * Creates new form EntradaBitacora
     */
    public EventoGeneralView() {
        initComponents();
        this.fechaCreacion = new Date();
        SimpleDateFormat df = new SimpleDateFormat(this.formatoFecha);
        this.fechaCreacionLabel.setText(df.format(fechaCreacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        detalle = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        borrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fechaCreacionLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiquietas = new javax.swing.JTextField();
        fechaEvento = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        detalle.setColumns(20);
        detalle.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        detalle.setLineWrap(true);
        detalle.setRows(2);
        jScrollPane2.setViewportView(detalle);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(filler1);

        borrar.setText("Borrar");
        borrar.setFocusable(false);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jToolBar1.add(borrar);

        jLabel1.setText("Creado el dia:");

        fechaCreacionLabel.setText("12/12/2012");

        jLabel4.setText("Fecha del evento:");

        jLabel3.setText("Etiquetas:");

        fechaEvento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaCreacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquietas, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquietas)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(fechaCreacionLabel)
                        .addComponent(fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        this.miBitacora.notificaBorrado(this);
    }//GEN-LAST:event_borrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JTextArea detalle;
    private javax.swing.JTextField etiquietas;
    private javax.swing.JLabel fechaCreacionLabel;
    private javax.swing.JSpinner fechaEvento;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
    //mis variables
    private BitacoraView miBitacora;
    private Date fechaCreacion;
    private String formatoFecha = "dd/MM/yy HH:mm";
    //mis metodos
    /**
     * @param bitacora la bitacora donde esta contenido este componente
     */
    public void setBitacora(BitacoraView bitacora){
        this.miBitacora = bitacora;
    }    

    @Override
    public Evento getData() {
        EventoGeneral r = new EventoGeneral();
        r.setDetalle(this.detalle.getText());
        r.setEtiquetas(this.etiquietas.getText());
        r.setFechaEvento((Date)this.fechaEvento.getValue());
        r.setFechaCreacion(this.fechaCreacion);
        return r;
    }

    public void loadData(EventoGeneral ev) {
        this.detalle.setText(ev.getDetalle());
        this.etiquietas.setText(ev.getEtiquetas());
        this.fechaEvento.setValue(ev.getFechaEvento());
        this.fechaCreacion = ev.getFechaCreacion();
        SimpleDateFormat df = new SimpleDateFormat(this.formatoFecha);
        this.fechaCreacionLabel.setText(df.format(fechaCreacion));
    }
}
